CMOR fixes for HadREM3-GA7-05
ESMValGroup/ESMValCore pull request #1062
Opened 2021-03-29 12:52 UTC by thomascrocker

CMOR fixes for HadREM3-GA7-05 CORDEX data. Follows similar approach to fixes for HadGEM2-ES etc.

-   Closes #1044

***

## Before you get started

-   [X] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## Checklist

-   [X] PR has a descriptive title for the [changelog](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [X] Labels are assigned so they can be used in the [changelog](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [X] Code follows the [style guide](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#code-style)
-   [ ] [Documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#documentation) is available for new functionality
-   [ ] YAML files pass [`pre-commit`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#pre-commit) or [`yamllint`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/community/introduction.html#yaml) checks
-   [ ] [Circle/CI tests pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [ ] [Codacy code quality checks pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [ ] [Documentation builds successfully](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review) on readthedocs
-   [ ] [Unit tests](https://docs.esmvaltool.org/projects/esmvalcore/projects/esmvalcore/en/latest/contributing.html#contributing-to-the-esmvalcore-package) are available

If you make backwards incompatible changes to the recipe format:

-   [ ] Update [ESMValTool](https://github.com/esmvalgroup/esmvaltool) and link the pull request(s) in the description

***

To help with the number pull requests:

-   🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValTool/pulls) in this repository

2021-03-29 12:53 UTC, thomascrocker commented
My first pull request. Feel free to assign me to review any other PRs if it would be useful.

2021-03-29 13:03 UTC, valeriupredoi commented
cheers @thomascrocker I'll have a looksee later today :+1:

2021-03-29 14:52 UTC, valeriupredoi requested changes
two minor Codacy issues. @jvegasbsc and @zklaus will know about CORDEX, I have very limited knowledge of that dataset unfortunately

2021-03-29 14:52 UTC, valeriupredoi commented on esmvalcore/cmor/_fixes/cordex/hadrem3_ga7_05.py
> +"""Fix HadREM3-GA7.05"""
```suggestion
"""Fix HadREM3-GA7.05."""
```

2021-03-29 14:52 UTC, valeriupredoi commented on esmvalcore/cmor/_fixes/cordex/hadrem3_ga7_05.py
> +        """Fix latitude and longitude
```suggestion
        """Fix latitude and longitude.
```

2022-06-17 13:39 UTC, nhsavage commented
how do we get this PR moving again please? should we do a new PR to check if it will merge to the latest head? What needs to be done to resolve the Codacy Static Code Analysis  problems?

2022-06-29 14:20 UTC, zklaus commented
Oh sorry guys, I just started using trello to organize my own ESMValTool work. I did not realize that the "Power-Up" I was using would place a backlink here.

Please disregard

PS: And now I found the switch to avoid that :facepalm:

2022-12-20 08:24 UTC, sloosvel commented
This fix got included in #1765

2022-12-20 08:24 UTC, closed without merging