Add a sorted print statement to
ESMValGroup/ESMValCore pull request #1225
Opened 2021-07-13 12:22 UTC by ledm

## Description

Closes #issue_number

Link to documentation:

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [ ] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [ ] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [ ] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [ ] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [ ] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [ ] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [ ] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [ ] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [ ] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [ ] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

2021-07-13 13:20 UTC, ledm commented on esmvalcore/_recipe_checks.py
> +                ", ".join(str(year) for year in sorted(missing_years)), input_files))
```suggestion
                ", ".join(str(year) for year in sorted(missing_years)), 
                input_files))
```

2021-07-13 13:33 UTC, valeriupredoi commented
@ledm please don't review your own PR, I know you want to make code changes straight in the we editor but do it via the edit code option not via review, reviewing your own PR adds confusion at review stage :beer:

2021-07-14 11:34 UTC, jvegasbsc requested changes

2021-07-14 11:34 UTC, jvegasbsc commented on esmvalcore/_recipe_checks.py
> +                ", ".join(str(year) for year in sorted(missing_years)),
To fix the codacy issues:

```suggestion
                ", ".join(str(year) for year in sorted(missing_years)),
```

2021-07-14 11:35 UTC, jvegasbsc commented
@ledm, can you also update it with the latest changes on main? It should fix the CircleCI error

2021-07-14 12:35 UTC, ledm commented
> @ledm, can you also update it with the latest changes on main? It should fix the CircleCI error

Done!

2021-07-14 13:06 UTC, jvegasbsc approved these changes

2021-07-14 13:06 UTC, merged