Test dtype in time preproc
ESMValGroup/ESMValCore pull request #1240
Opened 2021-07-20 12:03 UTC by jvegasbsc

This is a follow up from #1237.

It add checks for dtype conservation on time preprocessor tests

Closes #

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [ ] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [ ] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [ ] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [ ] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [ ] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [ ] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [ ] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [ ] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [ ] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [ ] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

2021-07-20 14:51 UTC, valeriupredoi commented on esmvalcore/preprocessor/_time.py
> +                                             operator='std_dev',
eugh! we really need to deactivate in-line comments from codecov, it makes review really annoying :confounded:

2021-07-21 12:24 UTC, jvegasbsc commented on esmvalcore/preprocessor/_time.py
> +                    "since the full time period of this dataset is not "
Testing one thing

2021-07-22 12:48 UTC, valeriupredoi commented on esmvalcore/preprocessor/_time.py
> +                                             operator='std_dev',
son of a moose, if you just press "a" on the keyboard you can toggle the codecove comments :grin:

2021-07-22 13:08 UTC, valeriupredoi approved these changes
nice ona Javi, one wee comment from me, it'd be good to print out an explanation if the dtype assertion fails

2021-07-22 13:08 UTC, valeriupredoi commented on tests/unit/preprocessor/_time/test_time.py
> +    """"Check data is identical to the expected one."""
all the `_time` functions apart from `climate_statistics` **should not** alter the `dtype` but if they do, there is no explicit check for that inside the respective function, so the test will fail with a very obscure assertion error, it's a good idea to plop a print statement here a la "Checking for dtype consistency between original cube data and preprocessor result" and then the developer will know what hit them

2021-07-22 14:27 UTC, valeriupredoi requested changes

2021-07-22 14:27 UTC, valeriupredoi commented on esmvalcore/preprocessor/_time.py
> -            raise ValueError(
so I was trying to write a test for this statement here a la:
```python
def test_standardized_anomalies_fail():
    """Test standardized ``anomalies`` failure due to shape mismatch."""
    cube = make_map_data(number_years=0.01)
    cube = cube[0:2]
    print(cube.coord("time"))
    with pytest.raises(ValueError):
        anomalies(cube, period="season", standardize=True)
```
which doesn't fail even if the cube's time axis is made up of two single points (two days) - surely this is something odd isn't it? Computing seasonal anomalies on two days should probably either fail or give the user a BIG warning data is totally unreliable?

2025-08-26 02:57 UTC, closed without merging