National Computing Infrastructure (NCI), Site specific configuration
ESMValGroup/ESMValCore pull request #2281
Opened 2023-12-18 23:48 UTC by rbeucher

## Description

I have added the configuration for our system down here in Australia.

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [X] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [X] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [X] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [X] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [ ] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [ ] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [X] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [ ] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [ ] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [ ] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

2023-12-18 23:49 UTC, rbeucher commented on esmvalcore/config-developer.yml
> +  input_file:
```suggestion
  input_file:
```

2023-12-18 23:49 UTC, rbeucher commented on esmvalcore/config-user.yml
> +#  ana4mips: default
```suggestion
#  ana4mips: default

```

2024-01-16 14:46 UTC, valeriupredoi requested changes
looks good and it's very welcome too, thanks @rbeucher! The only bit missing is adding a test for data finding on the new machine - that should be included here, but if you are not at ease plopping that test here, then I'd suggest letting this be merged, but open an issue and assign one of us tech cores to add it :beer:

2024-01-18 23:44 UTC, rbeucher commented
Thanks @valeriupredoi. I have added some tests. Anything else you think is missing?

2024-01-19 00:21 UTC, rbeucher commented
OK...it's failing of course. I'm looking into it...

2024-01-19 11:43 UTC, valeriupredoi approved these changes
brilliant! Very many thanks @rbeucher :beer:

2024-01-19 11:49 UTC, merged