Add custom CMO tables for ESACCI-PERMAFROST
ESMValGroup/ESMValCore pull request #2358
Opened 2024-03-04 08:48 UTC by axel-lauer

## Description

This PR adds custom CMOR tables for the following three ESACCI-PERMAFROST variables:

* active layer thickness (alt)
* permafrost ground temperature (gtd)
* permafrost extent (pfr)

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [ ] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [ ] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [ ] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [ ] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [ ] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [ ] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [ ] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [ ] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [ ] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

2025-12-05 10:10 UTC, bouweandela reviewed
It looks like there is also a derivation function in this pull request that is not mentioned in the description at the top. Is that intentional? If yes, please make sure that the derivation is lazy and add a unit test for it.

2025-12-05 10:10 UTC, bouweandela commented on esmvalcore/preprocessor/_derive/pfr.py
> +        soiltemp.data = da.where(soiltemp.data < THRESH_TEMPERATURE, 1, 0)
```suggestion
        soiltemp.data = da.where(soiltemp.core_data() < THRESH_TEMPERATURE, 1, 0)
```

2026-01-07 11:49 UTC, axel-lauer commented on esmvalcore/preprocessor/_derive/pfr.py
> +        soiltemp.data = da.where(soiltemp.data < THRESH_TEMPERATURE, 1, 0)
Done! Unit test is under development.

2026-01-09 13:01 UTC, axel-lauer commented on esmvalcore/preprocessor/_derive/pfr.py
> +        soiltemp.data = da.where(soiltemp.data < THRESH_TEMPERATURE, 1, 0)
A unit test for the new variable derivation script is now implemented.

2026-01-12 15:35 UTC, bouweandela commented on esmvalcore/preprocessor/_derive/pfr.py
> +    def required(project):
You can add the following to [ignore the `ruff` error](https://docs.astral.sh/ruff/linter/#comments) when running the pre-commit hooks:
```suggestion
    def required(project):  # noqa: ARG004
```

2026-01-12 15:37 UTC, bouweandela commented
If you click the `Update branch` button or run `git pull origin main --no-ff` and `git push` locally, the tests on CircleCI should run again.

2026-01-14 13:35 UTC, bouweandela requested changes

2026-01-14 13:35 UTC, bouweandela commented on esmvalcore/preprocessor/_derive/pfr.py
> +        mrsos_yr.data = da.where(mrsos_yr.data < 0.001, 0.0, 1.0)
Avoid loading all the data here:
```suggestion
        mrsos_yr.data = da.where(mrsos_yr.core_data() < 0.001, 0.0, 1.0)
```
see https://scitools-iris.readthedocs.io/en/stable/userguide/real_and_lazy_data.html for some further info

2026-01-14 13:35 UTC, bouweandela commented on esmvalcore/preprocessor/_derive/pfr.py
> +        mask = iris.analysis.maths.multiply(mrsos_yr, landfrac)
would it be possible to write
```suggestion
        mask = mrsos_yr * landfrac
```
instead?

2026-01-14 13:35 UTC, bouweandela commented on esmvalcore/preprocessor/_derive/pfr.py
> +        zmax = np.amax(z_coord.core_points())
The more commonly used function name is just `max`: https://numpy.org/devdocs/reference/generated/numpy.amax.html. Using that will make the code easier to read.
```suggestion
        zmax = np.max(z_coord.core_points())
```

2026-01-14 13:35 UTC, bouweandela commented on esmvalcore/preprocessor/_derive/pfr.py
> +            pfr_yr.data[tidx, :, :] = da.where(test_cube.data > 0.99, 1, 0)
Could this be replaced by the [`rolling_window_statistics`](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/api/esmvalcore.preprocessor.html#esmvalcore.preprocessor.rolling_window_statistics) preprocessor function? Something like:
```
pfr_yr = esmvalcore.preprocessor.rolling_window_statistics(
    soiltemp,
    coordinate="time",
    operator="mean",
    window_length=FROZEN_MONTHS,
)

2026-01-14 13:35 UTC, bouweandela commented on tests/unit/preprocessor/_derive/test_pfr.py
> +    np.testing.assert_array_equal(out_data, expected)
To make it easier to understand where something fails in a function, tests are typically split up into one test function per call to the function you're testing (`derived_var.calculate` in this case). So in this case, you could move this bit of code to a function called e.g. `test_pfr_calculation_minor_lat_lon_differences`, and the two further tests to e.g. `test_pfr_calculation_major_lat_differences` and `test_pfr_calculation_major_lon_differences`.

2026-01-14 13:35 UTC, bouweandela commented on tests/unit/preprocessor/_derive/test_pfr.py
> +    expected = 100.0 * np.ones_like(out_cube.data)
It would be nice to have a test case where not the entire cube is permafrost because this doesn't really check that the calculation is correct.

2026-01-14 13:35 UTC, bouweandela commented on esmvalcore/preprocessor/_derive/pfr.py
> +                )
It may be nice to use [`np.allclose`](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) here instead as that will correctly take into account negative differences too. For example:
```suggestion
    if np.allclose(x_coord1.core_points(), x_coord2.core_points(), atol=1.0e-4):
        x_coord2.points = x_coord1.points
        x_coord2.bounds = x_coord1.bounds
    else:
        logger.error("Longitudes of mrsos and stflf fields differ more than 1e-4 degrees.")
```

2026-01-15 08:03 UTC, axel-lauer commented on esmvalcore/preprocessor/_derive/pfr.py
> +        mask = iris.analysis.maths.multiply(mrsos_yr, landfrac)
This cannot be changed easily as `mrsos_yr` has a time coordinate, `landfrac` does not, which prevents plain multiplication of the two fields.

2026-01-15 14:12 UTC, axel-lauer commented on esmvalcore/preprocessor/_derive/pfr.py
> +            pfr_yr.data[tidx, :, :] = da.where(test_cube.data > 0.99, 1, 0)
Not sure. I tried a few options but could not reproduce the original output. Not sure it is worth spending much more time on this possible replacement.

2026-01-15 14:13 UTC, axel-lauer commented on esmvalcore/preprocessor/_derive/pfr.py
> +                )
Great idea. Changed as suggested.

2026-01-15 14:14 UTC, axel-lauer commented on tests/unit/preprocessor/_derive/test_pfr.py
> +    np.testing.assert_array_equal(out_data, expected)
Good point. I split the tests into separate functions.

2026-01-15 14:16 UTC, axel-lauer commented on esmvalcore/preprocessor/_derive/pfr.py
> +        zmax = np.amax(z_coord.core_points())
Didn't know. Changed as suggested.

2026-01-16 11:35 UTC, schlunma commented on esmvalcore/preprocessor/_derive/pfr.py
> +            pfr_yr.data[tidx, :, :] = da.where(test_cube.data > 0.99, 1, 0)
I `rolling_window_statistics` could be used if you extend the input cube by `test_period` time steps to both sides (the rolling window with a window > 1 will produce a shorter output cube; this accounts for that). Not sure if that's makes the code simpler, probably not...

2026-01-20 09:55 UTC, schlunma commented
Hello, this pull request has been marked with the `v2.14.0` milestone. The release of version 2.14.0 is currently scheduled for February 2026. To get this into the new release, it would be great to get this merged by the end of January.

If you won't be able to finish this in time, don't worry - just unassign the milestone `v2.14.0`. If you need any support, ping myself (@schlunma; the release manager for v2.14.0) or the @<span></span>ESMValGroup/technical-lead-development-team. Please note that I won't be available until the beginning of February, though.

2026-01-22 09:42 UTC, bouweandela commented on esmvalcore/preprocessor/_derive/pfr.py
> +            pfr_yr.data[tidx, :, :] = da.where(test_cube.data > 0.99, 1, 0)
```suggestion
            pfr_yr.data[tidx, :, :] = da.where(test_cube.core_data() > 0.99, 1, 0)
```
to avoid loading the data immediately

2026-01-22 09:56 UTC, axel-lauer commented on esmvalcore/preprocessor/_derive/pfr.py
> +            pfr_yr.data[tidx, :, :] = da.where(test_cube.data > 0.99, 1, 0)
Thanks!

2026-01-22 09:57 UTC, bouweandela commented on esmvalcore/preprocessor/_derive/pfr.py
> +            pfr_yr.data[tidx, :, :] = da.where(test_cube.data > 0.99, 1, 0)
It looks like the current implementation creates fairly [small dask chunks](https://blog.dask.org/2021/11/02/choosing-dask-chunk-sizes#too-small-is-a-problem), which may lead to slow/inefficient computations. Every time you create a dask array and use it to build another dask array, you insert all the dask chunks needed to build that subarray into the final array. Looping over the time-axis and computing things separately for each time step is a typical example of this. This may be aggravated by the use of `aggregated_by` https://github.com/sciTools/iris/issues/5455. Therefore, I think it would be worth investigating if `rolling_window_statistics` can be used to reduce the size of the Dask task graph and increase the chunk sizes.

However, maybe this works just fine, it's hard to tell from just looking at the code. Did you test the runtime? Can you run the computation using the [distributed scheduler](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/quickstart/configure.html#dask-distributed-scheduler-configuration)? And did you test how long it takes to compute a multi-model mean over e.g. 100 datasets?

It would be nice to have a good unit test, so we can look at improving computational performance later https://github.com/ESMValGroup/ESMValCore/pull/2358/files#r2690416067 if needed.

2026-02-04 08:58 UTC, schlunma commented
Sorry, it looks like we cannot reach a consensus on this in time for v2.14.0. Moving this to v2.15.0, please let me know if this causes any troubles.

2026-06-10 10:28 UTC, rbeucher commented
Hi all, as we prepare for the ESMValCore v2.15.0 release, the planned code freeze is 19 June 2026.

This PR is currently marked for the v2.15.0 milestone. Could you please confirm whether it should remain in scope for this release, or whether it would be better moved to a later milestone?

@flicj191 tagging you for release-freeze awareness.

2026-06-21 23:44 UTC, flicj191 commented
Hi all, sorry this couldn't be completed for 2.15, I will move this to 2.16. Let me know any issues.

2026-08-18 14:37 UTC, axel-lauer commented on esmvalcore/preprocessor/_derive/pfr.py
> +            pfr_yr.data[tidx, :, :] = da.where(test_cube.data > 0.99, 1, 0)
I revised calculation of the permafrost conditions, so now the `rolling_window_statistics` preprocessor is used as suggested (https://github.com/ESMValGroup/ESMValCore/pull/2358/commits/501c6f8b2cc45e0634f253c87028c536ca356e8f). The calculation is now done using yearly time steps, so I do not expect that performance will be an issue. I am now looking at the unit test, hopefully this can be merged then.

2026-08-19 08:50 UTC, axel-lauer commented on esmvalcore/preprocessor/_derive/pfr.py
> +            pfr_yr.data[tidx, :, :] = da.where(test_cube.data > 0.99, 1, 0)
The unit test now also includes a "no permafrost" test case: https://github.com/ESMValGroup/ESMValCore/pull/2358/changes/9a8e21797f68f0c6312c6296cab2555cd4e7c450

2026-08-19 08:50 UTC, axel-lauer commented on tests/unit/preprocessor/_derive/test_pfr.py
> +    expected = 100.0 * np.ones_like(out_cube.data)
Done: https://github.com/ESMValGroup/ESMValCore/pull/2358/changes/9a8e21797f68f0c6312c6296cab2555cd4e7c450

2026-08-19 08:51 UTC, axel-lauer commented
I think all comments are now addressed and this PR would be ready for merging.

2026-08-19 09:28 UTC, bouweandela commented on esmvalcore/preprocessor/_derive/pfr.py
> +            pfr_yr.data[tidx, :, :] = da.where(test_cube.data > 0.99, 1, 0)
Thanks Axel!

2026-08-19 10:04 UTC, bouweandela commented
Could you take a look at the output of `pre-commit run -a` please? There appear to be a few formatting and spelling issues. Technically, this looks good to me now, but it would need a scientific review as the algorithm is non-trivial.

2026-08-19 10:28 UTC, axel-lauer commented
Thanks @bouweandela ! I fixed the issues found by pre-commit here: https://github.com/ESMValGroup/ESMValCore/pull/2358/commits/3ea1cbd8916f610d40bb0ffe87be7574c6180419

@LisaBock it would be fantastic if you could do a scientific review...

2026-08-19 11:33 UTC, axel-lauer commented
@LisaBock Just in case, here is a recipe that could be used for testing: https://github.com/ESMValGroup/ESMValTool/blob/cmug_test_recipes/esmvaltool/recipes/esa/recipe_pfr_test.yml

2026-08-19 15:18 UTC, LisaBock approved these changes
Thanks @axel-lauer ! The run with the test recipe was successful and the results looks fine to me.

2026-08-19 15:46 UTC, bouweandela approved these changes

2026-08-24 11:55 UTC, schlunma commented
Thanks all!

2026-08-24 11:55 UTC, merged