Adding fix for ORAS5
ESMValGroup/ESMValCore pull request #2422
Opened 2024-05-17 10:18 UTC by jmalles

## Description

Fix for ORAS5. It includes the option to make the 'irregular' (2d) grid 'unstructured' (1d) and UGRID-compliant, which is the standard. To suppress this, one needs to add the extra facet 'make_unstructured: false' and/or 'ugrid: false' in the recipe.

The mesh description ('horizontal_grid' in the recipe) needs to be read from a file ([oras5_mesh.zip](https://github.com/ESMValGroup/ESMValCore/files/15347381/oras5_mesh.zip)), which is based on a file that can be downloaded [here](https://icdc.cen.uni-hamburg.de/thredds/catalog/ftpthredds/EASYInit/oras5/ORCA025/mesh/catalog.html?dataset=ftpthreddsscan/EASYInit/oras5/ORCA025/mesh/mesh_mask.nc).

Link to documentation: tba

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [ ] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [ ] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [ ] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [ ] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [ ] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [ ] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [ ] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [ ] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [ ] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [ ] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

2024-12-05 10:43 UTC, bettina-gier commented
Tried with the example recipe and it looks good, output seems as expected. Fast look through the code looks good. I'll do a more detailed review when I have more time.

2026-01-20 09:56 UTC, schlunma commented
Hello, this pull request has been marked with the `v2.14.0` milestone. The release of version 2.14.0 is currently scheduled for February 2026. To get this into the new release, it would be great to get this merged by the end of January.

If you won't be able to finish this in time, don't worry - just unassign the milestone `v2.14.0`. If you need any support, ping myself (@schlunma; the release manager for v2.14.0) or the @<span></span>ESMValGroup/technical-lead-development-team. Please note that I won't be available until the beginning of February, though.

2026-02-03 10:40 UTC, schlunma commented
I am sorry, it looks like this pull request won't make it into v2.14.0. If there are strong objections, please let me know. Moving this to v2.15.0.

2026-05-20 11:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ESMValGroup/ESMValCore?pullRequest=2422) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/ESMValGroup/ESMValCore?pullRequest=2422) before we can accept your contribution.<br/>**4** out of **5** committers have signed the CLA.<br/><br/>:white_check_mark: katjaweigel<br/>:white_check_mark: valeriupredoi<br/>:white_check_mark: bouweandela<br/>:white_check_mark: jmalles<br/>:x: Jan-Hendrik Malles<br/><hr/>**Jan-Hendrik Malles** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ESMValGroup/ESMValCore?pullRequest=2422) it.</sub>

2026-06-10 10:28 UTC, rbeucher commented
Hi all, a quick note for the ESMValCore v2.15.0 release: the planned code freeze date is 19 June 2026.

This PR is currently included in the v2.15.0 milestone. Could you please confirm whether it is still intended for this release and what needs to happen before it can be merged?

@flicj191 tagging you for release planning visibility.

2026-06-11 08:15 UTC, jmalles commented
Hello, I will try to get the code coverage to 100% today or tomorrow. Then someone would need to review it, I suppose.

2026-06-12 09:51 UTC, bettina-gier commented
@ghossh Hey Supriyo, Jan has updated the tests now to increase the coverage. Can you have a look and do a review please? <3

2026-06-12 10:25 UTC, ghossh commented
Hi @bettina-gier , I'm going on holiday after today and coming back on 28th Jun. I'll take a look afterward.

2026-06-12 11:39 UTC, bettina-gier commented
ah nvm then, that's after the core feature freeze where we want to have this in. I'll see if I can do it next week instead then..

2026-06-18 04:35 UTC, flicj191 commented on esmvalcore/config-developer.yml
I believe this was added before the current [configuration changes](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/quickstart/configure.html#developer-configuration-file). this may need to be updated similar to something like [data-native-icon.yml](https://github.com/ESMValGroup/ESMValCore/blob/main/esmvalcore/config/configurations/data-native-icon.yml)? or a hpc data file? and remove the lines from this file

2026-06-18 11:42 UTC, bettina-gier approved these changes
It runs, results look fine. Might be nice to add a sample config for the filename even if it's in a flat folder.

@alistairsellar Is it possible to do some sort of manual CLA override? Jan signed on the github account but most commits are under a faulty config that can't sign. Otherwise we would have to somehow rebase the commits.

2026-06-19 11:23 UTC, alistairsellar commented
> Is it possible to do some sort of manual CLA override?

Hi @bettina-gier. There's no way to override the CLA list of signatories if GitHub doesn't think that a commit is linked to a GitHub account. What I would suggest is that if you know for certain that all commits in a PR have been made by people who have signed the CLA (like in this case), then you can temporarily switch off the branch protection that looks at the CLA check. (This aligns with the spirit of why we need the CLA.) And then switch the rule back on again after the PR is merged.

Happy to do the switch-off when you're ready to merge, though I expect you've got permissions to change rules?

2026-06-19 11:27 UTC, bettina-gier commented
I personally don't have permissions for that I believe. I'll ask for a quick final tech review before merge!

2026-06-19 12:24 UTC, bouweandela requested changes
Looks good! To wrap it up, could you please add a bit more documentation about the various facets that can be used from the recipe to control the grid and remove code that was copy/pasted from the ICON fix but does not apply to ORAS5?

2026-06-19 12:24 UTC, bouweandela commented on esmvalcore/cmor/_fixes/native6/oras5.py
> +            NotImplementedError.
typically you would use a `KeyError` for this, or possibly a `ValueError`. `NotImplementedError` is for things that have not (yet) been implemented.

2026-06-19 12:24 UTC, bouweandela commented on esmvalcore/cmor/_fixes/native6/oras5.py
> +            )
```suggestion
            raise NotImplementedError(msg)
```

2026-06-19 12:24 UTC, bouweandela commented on esmvalcore/cmor/_fixes/native6/oras5.py
> +        u_grid = self.extra_facets.get("ugrid", False)
I see that there are multiple facets that may be specified in the recipe to make this data work. Could you please add documentation for those?

2026-06-19 12:24 UTC, bouweandela commented on esmvalcore/cmor/_fixes/native6/oras5.py
> +            )
```suggestion
            raise ValueError(msg)
```

2026-06-19 12:24 UTC, bouweandela commented on doc/develop/fixing_data.rst
> +<https://github.com/ESMValGroup/ESMValCore/blob/main/esmvalcore/cmor/_fixes/native6/oras5.py>`__,
```suggestion
```
these are intended as examples, there is no need to list everything and three examples seems a bit much

2026-06-19 12:24 UTC, bouweandela commented on esmvalcore/cmor/_fixes/native6/oras5.py
> +        # Get the unique nodes as dask arrays
Any particular reason for switching to Dask arrays here? They are typically slower, so usually you would only do this if the memory consumption is more than what is available, but in this case I doubt that there will be any memory saving because the array is backed by a numpy array and I don't see any obvious broadcasting that would increase the size of the array. But maybe I'm missing something?

2026-06-19 12:24 UTC, bouweandela commented on tests/integration/cmor/_fixes/native6/test_oras5.py
> +    session = CFG.start_session("my session")
Please use the `session` fixture instead.

2026-06-19 12:24 UTC, bouweandela commented on tests/integration/cmor/_fixes/native6/test_oras5.py
> +    session = CFG.start_session("my session")
Please use the `session` fixture instead.

2026-06-19 12:24 UTC, bouweandela commented on esmvalcore/cmor/_fixes/native6/oras5.py
> +            "Horizontal grid file",
Please add documentation on how to use these facets

2026-06-19 12:24 UTC, bouweandela commented on esmvalcore/cmor/_fixes/native6/oras5.py
> +        cubes = self.add_additional_cubes(cubes)
Is this feature needed for ORAS5?

2026-06-19 12:24 UTC, bouweandela commented on tests/integration/cmor/_fixes/native6/test_oras5.py
> +    # Remove latitude from tas cube to test automatic addition
This comment appears multiple times throughout this file but does not seem to be related to the test it is part of. Is it a result of copy/pasting another test and modifying that?

2026-06-19 12:24 UTC, bouweandela commented on tests/integration/cmor/_fixes/native6/test_oras5.py
> +    fix._shift_time_coord(cube, time_coord)
This test appears to have been copy/pasted from https://github.com/ESMValGroup/ESMValCore/blob/4f65a7bc8840d3a52920c93176446fd637470357/tests/integration/cmor/_fixes/icon/test_icon.py#L1872-L1962. Since the `_shift_time_coord` method is only defined on the base class and not modified in the file `oras5.py`, there is no need to test it again. To keep the code easy to maintain, I would suggest removing it here. The same goes for the other copy/pasted tests further down that do not apply to the oras5.py file.

2026-06-22 06:38 UTC, jmalles commented on esmvalcore/cmor/_fixes/native6/oras5.py
> +        # Get the unique nodes as dask arrays
Makes sense. Unfortunately, the dask.array.unique function does not support the axis argument.

2026-06-22 06:41 UTC, jmalles commented on esmvalcore/cmor/_fixes/native6/oras5.py
> +        cubes = self.add_additional_cubes(cubes)
Probably not.

2026-06-22 06:44 UTC, jmalles commented on tests/integration/cmor/_fixes/native6/test_oras5.py
> +    # Remove latitude from tas cube to test automatic addition
Removed where inappropriate

2026-06-22 07:37 UTC, jmalles reviewed
Hopefully, all comments are addressed now. Otherwise, let me know!

2026-06-22 08:47 UTC, bouweandela commented on tests/integration/cmor/_fixes/native6/test_oras5.py
> +)
Retrieving a grid file from a URL does not seem to be something the code in the `oras5.py` file supports, so why is this here?

2026-06-22 08:49 UTC, bouweandela commented on doc/quickstart/find_data.rst
> +  the ``raw_name`` of the unrotated velocities in the recipe.
Can you give a bit more detail here? What is `raw_name`? What would be acceptable values?

2026-06-22 08:57 UTC, bouweandela commented on tests/integration/cmor/_fixes/native6/test_oras5.py
> +def check_model_level_metadata(cube):
This function appears to be unused, why is it here?

2026-06-22 08:58 UTC, bouweandela commented on tests/integration/cmor/_fixes/native6/test_oras5.py
> +    fix.fix_metadata(cubes)
What desired property of the code does this test? Could you either update the function name of the test so that it is clear what is being tested or add a comment or docstring to describe that? Should there be some checks on the result?

2026-06-22 09:02 UTC, bouweandela commented
> Hopefully, all comments are addressed now. Otherwise, let me know!

Thanks, mostly good now! I found a few more things in the tests that appear to be unused and the documentation could be a bit more clear.

2026-06-22 09:10 UTC, jmalles commented on tests/integration/cmor/_fixes/native6/test_oras5.py
> +)
Removed

2026-06-22 09:10 UTC, jmalles commented on tests/integration/cmor/_fixes/native6/test_oras5.py
> +def check_model_level_metadata(cube):
It is now in use

2026-06-22 09:28 UTC, jmalles commented on tests/integration/cmor/_fixes/native6/test_oras5.py
> +    fix.fix_metadata(cubes)
Replaced by more appropriate tests

2026-06-22 10:02 UTC, jmalles commented on doc/quickstart/find_data.rst
> +  the ``raw_name`` of the unrotated velocities in the recipe.
Done

2026-06-22 10:08 UTC, jmalles reviewed
I addressed the comments and hope this is good to go now! 🙂

2026-06-22 10:11 UTC, bouweandela commented on doc/quickstart/find_data.rst
> +  ``vomecrty``and ``vozocrtx``, instead of ``vomecrtn`` and ``vozocrte``, for
```suggestion
  ``vomecrty`` and ``vozocrtx``, instead of ``vomecrtn`` and ``vozocrte``, for
```

2026-06-22 10:13 UTC, bouweandela approved these changes
Thanks, looks good to me now

2026-06-22 10:19 UTC, merged

2026-06-22 10:55 UTC, jmalles commented
Thank you all, I am happy that this is finally done! 🙂