Allow `fix_file` to return `Cube` and `CubeList` objects
ESMValGroup/ESMValCore pull request #2579
Opened 2024-11-12 14:20 UTC by schlunma

## Description

Currently, if a file cannot be properly read with Iris, we use `fix_file` to create a copy of that file and modify it using `netCDF4.Dataset` ([example](https://github.com/ESMValGroup/ESMValCore/blob/c792a523569ea1ccc3fb49cdef84b0d6ccbbecc3/esmvalcore/cmor/_fixes/cmip6/cesm2_waccm.py#L15-L49)). This is very inefficient and slow.

A much better way to deal with this is to read the file with [ncdata](https://ncdata.readthedocs.io/en/latest/) or [xarray](https://docs.xarray.dev/en/stable/index.html) and then use ncdata to convert that object to an Iris object. However, for this to work, we need to allow `fix_file` to return Iris objects (instead of paths) and `load` to read Iris objects (instead of paths). This PR does that.

It also provides a convenience function `dataset_to_iris` that allows to convert an xarray or ncdata object to an Iris object very similar to our `load` function.

Closes https://github.com/ESMValGroup/ESMValCore/issues/2129
Related to https://github.com/ESMValGroup/ESMValCore/issues/674

Link to documentation:

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [ ] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

2025-05-12 07:54 UTC, schlunma commented
One more incentive why it would be great to have this feature:

```py
path = "/path/to/real_EMAC_file_with_855_variables.nc"

%%timeit
iris.load(path)
# 1min 47s ± 446 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

%%timeit
xr.open_dataset(path, chunks="auto")
# 277 ms ± 8.14 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

%%timeit
netCDF4.Dataset(path, mode="r")
# 5.2 ms ± 23.7 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

This uses the most up-to-date versions of all these packages (fresh install from 2025-05-09).

Since we sometimes need to read hundreds of those files (this example only contains a single time step), ESMValTool can spend hours just loading these datasets.

2025-05-16 08:41 UTC, schlunma commented
The missing tests here reported by codecov are in `esmvalcore/cmor/_fixes/ipslcm/ipsl_cm6.py`. In this file, I just renamed the argument `filepath` to `file`. Since adding tests for this is not trivial, I will skip that here.

2025-05-27 15:26 UTC, bouweandela approved these changes
Thanks @schlunma, I think this is a great first step towards supporting reading data from something else than posix filesystems.

2025-05-27 15:26 UTC, bouweandela commented on tests/integration/preprocessor/_io/test_load.py
> +    mock_load_raw.side_effect = load_with_warning
Using the `mocker` fixture might be nice here:
```suggestion
def test_do_not_ignore_warnings(mocker):
    """Test do not ignore specific warnings."""
    mocker.patch.object(iris, "load_raw", autospec=True, side_effect=load_with_warning)
```

2025-05-27 15:26 UTC, bouweandela commented on tests/integration/preprocessor/_io/test_load.py
> +    np.testing.assert_equal(cube.data, [1, 2])
Use `assert_array_equal` from the `tests` module here too?

2025-05-27 15:26 UTC, bouweandela commented on tests/__init__.py
> +def create_realistic_4d_cube():
It would be more in line with the pytest style of using fixtures to define this is a fixture in conftest.py

2025-05-27 15:26 UTC, bouweandela commented on esmvalcore/preprocessor/_io.py
> +            logger.warning(
Should we raise an exception for this? If it is only expected to happen when people contribute new fixes, I would raise an exception to make sure we don't bother users with many warnings. On the other hand, if it could happen to users, maybe it should be a debug log message instead?

2025-05-28 10:55 UTC, schlunma commented on tests/integration/preprocessor/_io/test_load.py
> +    np.testing.assert_equal(cube.data, [1, 2])
Done in https://github.com/ESMValGroup/ESMValCore/pull/2579/commits/24bc1500089e9962c55d4a852b8fabfc3fc166e4.

2025-06-03 13:49 UTC, schlunma commented on esmvalcore/preprocessor/_io.py
> +            logger.warning(
It might be better to raise an actual `ESMValCoreUserWarning` instead of using the logger since this problem can only occur when using the Python API. This makes it much more straightforward to ignore the warning if required. @bouweandela what do you think?

2025-06-03 14:28 UTC, bouweandela commented on esmvalcore/preprocessor/_io.py
> +            logger.warning(
Sounds good!

2025-06-04 07:38 UTC, schlunma commented on esmvalcore/preprocessor/_io.py
> +            logger.warning(
Done in https://github.com/ESMValGroup/ESMValCore/pull/2579/commits/301930ea89d0b0df188aaa4325baacbab560d69c

2025-06-05 15:57 UTC, valeriupredoi commented
I agree with @bouweandela but could you pls point me where you are loading the file with `ncdata.NcData()` please? That should be a well defined and exceptioned function in `_io.py` that then is called from `load` :beer:

2025-06-05 16:09 UTC, valeriupredoi requested changes
Hi Manu, sorry for being a party pooper, but I have some concerns wrt the implementation, could you please have a look at my questions :beer:

2025-06-05 16:09 UTC, valeriupredoi commented on esmvalcore/cmor/_fixes/cmip6/cesm2.py
> +        file: str | Path,
that's a URI or a Path - it's not a `File` ie an open file object, is it? If not, pls don't call it `file`, that may be misleading

2025-06-05 16:09 UTC, valeriupredoi commented on esmvalcore/cmor/_fixes/cmip6/cesm2.py
> +        file : str
same here - `file` is usually an open file object or handler

2025-06-05 16:09 UTC, valeriupredoi commented on esmvalcore/iris_helpers.py
> +    return cubes
why are you calling the ncdata-iris lock share here (ie in this script) if the open file call is not here? The lock should be created when the file is opened, otherwise it's not gonna work. Which leads me to my main question, where do you open the file with ncdata?

2025-06-06 07:04 UTC, schlunma commented on esmvalcore/cmor/_fixes/cmip6/cesm2.py
> +        file: str | Path,
It's called `file` to be consistent with its [parent method](https://github.com/ESMValGroup/ESMValCore/blob/f3e48c986a0a3b722b6311365c650b257b2bb1a1/esmvalcore/cmor/_fixes/fix.py#L86), in which `file` can have the types `str | Path | xr.Dataset | ncdata.NcData`. I agree that `file` is not optimal, but couldn't think of something else. Do you have a better suggestion?

2025-06-06 07:20 UTC, schlunma commented on esmvalcore/iris_helpers.py
> +    return cubes
> why are you calling the ncdata-iris lock share here (ie in this script) if the open file call is not here?

As far as I understand the [doc](https://ncdata.readthedocs.io/en/latest/details/api/ncdata.threadlock_sharing.html#module-ncdata.threadlock_sharing) and the [code](https://github.com/pp-mo/ncdata/blob/16d60e5c147a469474503f2c2cf565351b3e20f9/lib/ncdata/threadlock_sharing.py#L64-L119), it doesn't matter where you call this function, as long as it's in the main thread. @pp-mo is that assumption correct?

Since the function [`dataset_to_iris`](https://github.com/ESMValGroup/ESMValCore/blob/f3e48c986a0a3b722b6311365c650b257b2bb1a1/esmvalcore/iris_helpers.py#L588-L652) lives in this module, I thought this is the best place for now. Would you have another suggestion? It should be in a module that is also loaded when using our Python API (maybe simply in `ESMValCore/esmvalcore/__init__.py`?).

> where do you open the file with ncdata?

This PR only implements the support for opening files with ncdata or xarray in the `fix_file` function, but doesn't actually use that. I plan to implement this in a future (dataset-specific) PR. There's no file-opening happening with ncdata or xarray in this PR.

2025-06-06 13:40 UTC, valeriupredoi commented on esmvalcore/cmor/_fixes/cmip6/cesm2.py
> +        file: str | Path,
this is something I've always raked my brains with too - especially when `file` can be a `Dataset` - I'd call it `input_object` but no worries, let's not make a fuss of this, at least we have the typing on so it's visible what sort of structure it is

2025-06-06 13:44 UTC, valeriupredoi commented on esmvalcore/iris_helpers.py
> +    return cubes
OK, it makes sense, I was concerned about this previously thinking there was a call where the `ncdata.Dataset` is initialized and loaded, ie an actual open file call, there would have been the right place to create the lock, but since there is no such call, then this looks to be the right place (the to-iris bit justifies it)

2025-06-06 13:46 UTC, valeriupredoi approved these changes
> There's no file-opening happening with ncdata or xarray in this PR.

Bingo! Thanks, Manu! All clear to me now, sorry if I sounded like an old man yelling at the clouds :cloud:

2025-06-06 15:50 UTC, merged