Add ocean variable to the ACCESS Live CMORiser
ESMValGroup/ESMValCore pull request #2601
Opened 2024-12-02 06:29 UTC by rbeucher

## Description

Adds Ocean variable to the ACCESS Live CMORIser

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [ ] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [ ] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [ ] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [ ] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [ ] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [ ] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [ ] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [ ] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [ ] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [ ] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

2024-12-02 09:52 UTC, rbeucher commented
@rhaegar325 please check that I have not introduced any issues.
@flicj191. This is originally @rhaegar325's work. Please give it a try.

2024-12-03 03:20 UTC, rhaegar325 commented
HI, @valeriupredoi , this pr is about a new version of access on-the-fly cmoriser. we add some extra function to make it compatible with two ocean variable. could you please review and merge it if there is no conflict.

2024-12-03 14:50 UTC, valeriupredoi commented
many thanks folks, since @rbeucher assigned @flicj191 then I'll wait for her expert review then I'll have an overview looks and merge :+1:

2024-12-05 02:57 UTC, flicj191 requested changes
Thanks @rhaegar325 I was able to run a simple recipe and find the data. I've added comments to documentation.
Does still run very slow, it looks like it has to read from each file the date range as the file name (eg.`ocean_month.nc-20121231`) doesn't have the date surrounded by '_', '-', '.' as in this dataset part:
https://github.com/ESMValGroup/ESMValCore/blob/ea1734b16899881e7436da83f1eadadb0fc9a788/esmvalcore/local.py#L77C1-L82C34
maybe can add to here? @valeriupredoi @rbeucher 
not sure where's best to constrain reading specific variable from the file if that would improve? as each file might have like ~200cubes

2024-12-05 02:57 UTC, flicj191 commented on doc/quickstart/find_data.rst
> +``freq_attribute``   A special attribute in the filename    No default
As we are changing `special_attr` to freq`_attribute`  we need to edit above as well in lines 576 and 562.  Maybe also add for ocean directories and and files like line 561 and 562 
`'{dataset}/{sub_dataset}/{exp}/{modeling_realm}'`
`'ocean_{freq_attribute}.nc-*'`
and also add to the list of supported variables for ocean (ln 556/557)

2024-12-05 02:57 UTC, flicj191 commented on yz9299_ESMValTool.yml
this empty file can be removed

2024-12-05 06:19 UTC, rhaegar325 commented
Thanks @flicj191 for your review, I will remove the empty file. for the file-reading part, it is a problem and bother me for a long time, I think your suggestion could be a solution for this.

2024-12-05 13:15 UTC, rhaegar325 commented
Hi, @valeriupredoi, it seems that I don't have write access to this repo since I can not push my local branch, could you please give me the write permission so that I could manage the branch of this pr?

2024-12-09 05:06 UTC, flicj191 commented
> Thanks @rhaegar325 I was able to run a simple recipe and find the data. I've added comments to documentation. Does still run very slow, it looks like it has to read from each file the date range as the file name (eg.`ocean_month.nc-20121231`) doesn't have the date surrounded by '_', '-', '.' as in this dataset part: https://github.com/ESMValGroup/ESMValCore/blob/ea1734b16899881e7436da83f1eadadb0fc9a788/esmvalcore/local.py#L77C1-L82C34 maybe can add to here? @valeriupredoi @rbeucher not sure where's best to constrain reading specific variable from the file if that would improve? as each file might have like ~200cubes

I have edited the `local.py` so it can find the right files by date without loading, though not sure if this is the best was and the affect on other files. Will have to find the ruff format error it added, sorry!

Having a look at the test dataset (`- {project: ACCESS, dataset: ACCESS-ESM1-5, mip: Omon, sub_dataset: HI-CN-05, exp: history, 
    freq_attribute: month, start_year: 2000, end_year: 2005}`)
The raw data has latitude and longitude as both dimension coordinate and auxiliary coordinate, so both 1D and 2D. This one could be a regular grid so maybe to fix we can remove the auxiliary coordinates? we may need to check with the modellers? 
Otherwise, we should also add the `areacello` variable to be added as a 'supplementary variable' so that it can do area_statistics.

2024-12-09 09:00 UTC, rbeucher commented
Thanks for your help with this @flicj191

2024-12-09 23:17 UTC, rhaegar325 commented
Really appreciate for your help and your advice @flicj191

2025-02-19 06:03 UTC, rhaegar325 commented
Hi @valeriupredoi, I have a question about the load the  supplementary data in the live-cmoriser. I am making the live-cmoriser compatiable with ocean variables, and ocean variable have a special grid for the latitude and longitude, so I may need to load it while cmorising. I was wondering if there is any method allow me to load data store in `.nc` file while the live-cmoriser is working?

2025-02-19 13:58 UTC, valeriupredoi commented
> Hi @valeriupredoi, I have a question about the load the supplementary data in the live-cmoriser. I am making the live-cmoriser compatiable with ocean variables, and ocean variable have a special grid for the latitude and longitude, so I may need to load it while cmorising. I was wondering if there is any method allow me to load data store in `.nc` file while the live-cmoriser is working?

best person to answer that question is Manuel @schlunma mate - I have very little knowledge of the on-the-fly cmorizers, unfortunately. Manu, could you assist here, when you have a minute, please buds? :beer:

2025-02-19 16:22 UTC, schlunma commented
I am not sure I understand what you mean. Are you referring to supplementary variables (like grid cell areas, land/sea fractions, etc.)? See [here](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/recipe/preprocessor.html#supplementary-variables-ancillary-variables-and-cell-measures) for details on that. If you're referring to other netcdf files that contain other variables, have a look at the [ICON fix](https://github.com/ESMValGroup/ESMValCore/blob/8f94879b76ae25b3be8af2a9071ecf7d7683023d/esmvalcore/cmor/_fixes/icon/_base_fixes.py#L384), where we also load another file that describes the horizontal grid during the fix.

Also, I am very hesitant about the change in `local.py`. This has the potential to break data finding in other circumstances. I think we should fix this properly during the implementation of https://github.com/ESMValGroup/ESMValCore/issues/2584. There is also an open issue about this: https://github.com/ESMValGroup/ESMValCore/issues/1078

2025-02-27 01:20 UTC, rhaegar325 commented
Hi, @valeriupredoi @schlunma , really appreciate for your suggestion about our pr, that's really helpful. Now we have solved all the issues and this pr is ready to be reviewed and merged. Please review it when it's convenient for you. Thanks again for all the suggestions and help.

2025-03-03 04:17 UTC, rbeucher commented
@charles-turner-1 do you think you can review that one for us please?

2025-03-03 04:40 UTC, charles-turner-1 requested changes
Couple of thing related to numpy arrays that I think would be useful to change for performance/readability.

Otherwise looks good - although I don't know enough about the logic of the CMORIsers so my opinion isn't worth much there.

2025-03-03 04:40 UTC, charles-turner-1 commented on esmvalcore/cmor/_fixes/access/_base_fix.py
> +        name_list = self.extra_facets.get("raw_name", self.vardef.short_name)
Duplicate line here

2025-03-03 04:40 UTC, charles-turner-1 commented on esmvalcore/cmor/_fixes/access/_base_fix.py
> +        cube.dim_coords[-2].points = np.array([int(i) for i in range(300)])
`np.arange(300)` here will give the same result as `np.array([int(i) for i in range(300)])` should be much faster.

2025-03-03 04:40 UTC, charles-turner-1 commented on esmvalcore/cmor/_fixes/access/_base_fix.py
> +        cube.dim_coords[-1].points = np.array([int(i) for i in range(360)])
As above, => `np.arange(360)`

2025-03-03 04:40 UTC, charles-turner-1 commented on esmvalcore/cmor/_fixes/access/_base_fix.py
> +                [j + 360 for j in i if j < 0] + [j for j in i if j >= 0]
Assuming this is a numpy array, you can write this as `temp_points.append( j % 360)` which is (IMO) easier to read, and won't run into any potential ordering issues. It'll also be substantially faster.

2025-03-03 04:40 UTC, charles-turner-1 commented on esmvalcore/cmor/_fixes/access/_base_fix.py
> +            temp_points.append([j.astype(np.float64) for j in i])
I think this whole type conversion operation can be done in a single instruction, which again should be quite a lot faster:
`np.array(i, dtype=np.float64)`

Probably possible to remove the whole loop depending on the type of `cube.aux_coords[-2].points`, eg:
```python 
temp_points = np.array(cube.aux_coords[-2].points,dtype=np.float64)
```

2025-03-03 04:40 UTC, charles-turner-1 commented on tests/integration/cmor/_fixes/access/test_access_esm1_5.py
> +    [int(i) for i in range(1, 13)],
Probably easier to just write `list(range(1,13))` here

2025-03-03 04:40 UTC, charles-turner-1 commented on tests/integration/cmor/_fixes/access/test_access_esm1_5.py
> +        cube.dim_coords[-2].points == np.array([int(i) for i in range(300)])
`np.array([int(i) for i in range(300)])` => `np.arange(300)`

2025-03-03 04:40 UTC, charles-turner-1 commented on tests/integration/cmor/_fixes/access/test_access_esm1_5.py
> +        cube.dim_coords[-1].points == np.array([int(i) for i in range(360)])
`np.array([int(i) for i in range(360)])` => `np.arange(360)`

2025-03-03 04:43 UTC, charles-turner-1 commented on esmvalcore/cmor/_fixes/access/_base_fix.py
> +                [j + 360 for j in i if j < 0] + [j for j in i if j >= 0]
Probably also the case that this whole loop can be written as 
```python
temp_points = cube.aux_coords[-1].points % 360
```
, similarly to what I suggested below - although I'd check this a little more carefully.

2025-03-03 04:54 UTC, rhaegar325 commented on esmvalcore/cmor/_fixes/access/_base_fix.py
> +        name_list = self.extra_facets.get("raw_name", self.vardef.short_name)
Thanks charles for pointing that out, it might have been caused by the auto-merge

2025-03-03 05:46 UTC, charles-turner-1 commented on esmvalcore/cmor/_fixes/access/_base_fix.py
> +            temp_points.append([j % 360 for j in i])
This doesn't need to be a list comprehension - you should be able to replace with either 
```python
temp_points = []       
for i in cube.aux_coords[-1].points:
    temp_points.append(i % 360)
``` 
or potentially - double check this is valid, I think it should be 
```python
temp_points = cube.aux_coords[-1].points % 360
```

2025-03-11 03:07 UTC, charles-turner-1 approved these changes

2025-03-11 07:53 UTC, merged