Add instructions how to use esmavltool from HPC central installations
ESMValGroup/ESMValCore pull request #841
Opened 2020-10-20 15:40 UTC by valeriupredoi

This is to tell users about the readily available central installations at JASMIN and DRKZ - I filled in the bits for Jasmin, @bjoernbroetz would you be able to get the info in for DKRZ pls mate :beer: 

Before you start, please read our [contribution guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html).

**Tasks**

-   [ ] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [ ] This pull request has a descriptive title that can be used in a changelog
-   [ ] Add unit tests
-   [ ] Public functions should have a numpy-style docstring so they appear properly in the [API documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/api/esmvalcore.html). For all other functions a one line docstring is sufficient.
-   [ ] If writing a new/modified preprocessor function, please update the [documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/recipe/preprocessor.html)
-   [ ] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out why.
-   [ ] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask by commenting.
-   [ ] Please use `yamllint` to check that your YAML files do not contain mistakes
-   [ ] If you make backward incompatible changes to the recipe format, make a new pull request in the [ESMValTool repository](https://github.com/ESMValGroup/ESMValTool) and add the link below

If you need help with any of the tasks above, please do not hesitate to ask by commenting in the issue or pull request.

* * *

Closes #issue_number

2020-12-07 13:11 UTC, valeriupredoi commented
@bjoernbroetz @remi-kazeroni can you guys pls have a look at this and add the DKRZ bits pls :beer:

2021-01-27 17:08 UTC, valeriupredoi commented
ping @remi-kazeroni - it'd be good to have this feature documented in v2.2 :+1:

2021-01-28 08:36 UTC, remi-kazeroni commented
> ping @remi-kazeroni - it'd be good to have this feature documented in v2.2 👍

Good point! I'll ask the people in charge of the central installation at DKRZ what is the status of that 👍

2021-02-08 12:02 UTC, valeriupredoi commented
any news here? @remi-kazeroni - Javi and me will get more changes in the release later on in a couple hours so you still have a bit of time, but after that I'd like to merge it, and if no info on DKRZ side we'll do it next (bugfix) release

2021-02-08 12:05 UTC, remi-kazeroni commented
> 
> 
> any news here? @remi-kazeroni - Javi and me will get more changes in the release later on in a couple hours so you still have a bit of time, but after that I'd like to merge it, and if no info on DKRZ side we'll do it next (bugfix) release

Sorry I have not heard back from DKRZ about the status of the central installation. I guess this is still ongoing. Hopefully we can include this in the next release.

2021-02-08 12:07 UTC, valeriupredoi commented
do you at least know how to module load/activate env to get esmvaltool in path and run stuff on DKRZ? Or is that the info that you wanted to find out from the IT folk

2021-02-08 12:22 UTC, remi-kazeroni commented
> 
> 
> do you at least know how to module load/activate env to get esmvaltool in path and run stuff on DKRZ? Or is that the info that you wanted to find out from the IT folk

I'm still waiting for the esmvaltool module to be created

2021-02-08 12:28 UTC, valeriupredoi commented
> > do you at least know how to module load/activate env to get esmvaltool in path and run stuff on DKRZ? Or is that the info that you wanted to find out from the IT folk
> 
> I'm still waiting for the esmvaltool module to be created

aha! That changes the status quo - I'll merge only with JASMIN info, keep the issue open and you should tell the IT folk to depeche mode :grin:

2021-02-08 12:30 UTC, valeriupredoi commented
blergh this is actually my PR so @jvegasbsc could you pls approve and merge matey :beer:

2021-02-09 08:56 UTC, jvegasbsc requested changes

2021-02-09 08:56 UTC, jvegasbsc commented on doc/quickstart/install.rst
> + - DKRZ: Bjoern please
Remove this and we are ok
```suggestion
```

2021-02-09 14:31 UTC, jvegasbsc approved these changes

2021-02-09 14:31 UTC, merged