Add support for unstructured grids
ESMValGroup/ESMValCore pull request #965
Opened 2021-01-27 13:08 UTC by jvegasbsc

## Description
We currently can not work with unstructured grids because they fail the monotonicity check. This PR fixes this by skipping the check when we detect an unstructured grid, as we do for the irregular ones when `ndim` of `lat` and `lon` is greather than one.

I opted for a fairly easy way to detect those grids:  look for `ndim` == 1 and `lat`and `lon` sharing the same dimension

-   Closes #751

***

## Before you get started

-   [ ] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## Checklist

-   [ ] PR has a descriptive title for the [changelog](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [ ] Code follows the [style guide](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#code-style)
-   [ ] [Documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#documentation) is available for new functionality
-   [ ] YAML files pass [`pre-commit`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#pre-commit) or [`yamllint`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/community/introduction.html#yaml) checks
-   [ ] [Circle/CI tests pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [ ] [Codacy code quality checks pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [ ] [Documentation builds successfully](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review) on readthedocs
-   [ ] [Unit tests](https://docs.esmvaltool.org/projects/esmvalcore/projects/esmvalcore/en/latest/contributing.html#contributing-to-the-esmvalcore-package) are available

If you make backwards incompatible changes to the recipe format:

-   [ ] Update [ESMValTool](https://github.com/esmvalgroup/esmvaltool) and link the pull request(s) in the description

***

To help with the number pull requests:

-   🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValTool/pulls) in this repository

2021-01-28 10:24 UTC, koldunovn approved these changes
Thanks a lot for doing this, @jvegasbsc ! Looks good to me. The assumption of the same sized 1d coordinate is not necessary mean unstructured mesh, one can have a setup on regular grid with same number of lons and lats (some crazy regional model), but better to be practical :)

2021-01-28 10:28 UTC, jvegasbsc commented
> Thanks a lot for doing this, @jvegasbsc ! Looks good to me. The assumption of the same sized 1d coordinate is not necessary mean unstructured mesh, one can have a setup on regular grid with same number of lons and lats (some crazy regional model), but better to be practical :)

Is not checking is the same size, it is checking is the same dimension in the cube (see https://scitools-iris.readthedocs.io/en/latest/generated/api/iris/cube.html?highlight=coord_dims#iris.cube.Cube.coord_dims) so it should be safer

2021-01-29 12:31 UTC, Peter9192 requested changes
Checking in to offload Bouwe. Code make sense to me. Just one suggestion, a question, and a typo. 
If you can point me to a nice example cube with unstructured data I could do a more thorough check, but maybe that's not necessary if one of the other reviewers did it. 
Cheers! @jvegasbsc

2021-01-29 12:31 UTC, Peter9192 commented on esmvalcore/cmor/check.py
> +        if self._is_unestructured_grid and \
Wondering if it would make sense to make `_is_unstructured` a class method/property. Then you wouldn't have to initialize it in `_check_coords()`

2021-01-29 15:20 UTC, jvegasbsc commented on esmvalcore/cmor/check.py
> +        if self._cube.coords('latitude') and self._cube.coords('longitude'):
Old code, will clean

2021-01-29 15:40 UTC, bouweandela commented
> If you can point me to a nice example cube with unstructured data I could do a more thorough check

You can find the name of the model and variable in the linked issue, it would be great if you could try running a recipe to make sure it really works.

2021-01-29 16:06 UTC, jvegasbsc commented
This set of HighRESMIP experiments, for example. Be aware that you may need some extra tags, as I run this in our local copies of the data

```yaml
     - {dataset: CESM1-CAM5-SE-HR, project: CMIP6, exp: hist-1950, start_year: 1960, end_year: 2014, ensemble: r1i1p1f1, grid: gn, mip: Amon}
     - {dataset: CESM1-CAM5-SE-LR, project: CMIP6, exp: hist-1950, start_year: 1960, end_year: 2014, ensemble: r1i1p1f1, grid: gn, mip: Amon}
     - {dataset: CESM1-CAM5-SE-HR, project: CMIP6, exp: highres-future, start_year: 2015, end_year: 2050, ensemble: r1i1p1f1, grid: gn, mip: Amon}
     - {dataset: CESM1-CAM5-SE-LR, project: CMIP6, exp: highres-future, start_year: 2015, end_year: 2050, ensemble: r1i1p1f1, grid: gn, mip: Amon }
```

2021-02-01 10:00 UTC, Peter9192 commented
> This set of HighRESMIP experiments, for example. 

Thanks, that seems to work like a charm 👍  

Now we just need to make sure that the checks pass. The docs build is fixed here: https://github.com/ESMValGroup/ESMValCore/pull/964.

2021-02-01 12:23 UTC, jvegasbsc commented
Checks work, codacy down.

2021-02-01 18:55 UTC, nielsdrost commented
Seems like Codacy is spitting out another warning. Can you see if this is fixable @jvegasbsc ?

2021-02-01 20:37 UTC, jvegasbsc commented
Sorry for dismissing your review @Peter9192 , but the check pass and the codacy issue is solved now, and we want this in 2.2

2021-02-01 20:37 UTC, merged

2021-02-02 07:40 UTC, Peter9192 commented
> 
> 
> Sorry for dismissing your review @Peter9192 , but the check pass and the codacy issue is solved now, and we want this in 2.2

No problem! Sorry I didn't get back to it soon enough.